openapi: 3.0.0
info:
  license:
    name: MIT
  title: Swagger Dummy Posts
  version: 1.0.0
servers:
- url: http://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      operationId: fetchPosts
      parameters:
      - description: How many items to return at one time (max 100)
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posts'
          description: A paged array of posts
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: List all posts
      tags:
      - posts
    post:
      operationId: createPosts
      responses:
        "201":
          description: Null response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Create a post
      tags:
      - posts
  /posts/{id}:
    get:
      operationId: getPostById
      parameters:
      - description: The id of the post to retrieve
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: Expected response to a valid request
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Info for a specific post
      tags:
      - posts
components:
  schemas:
    Post:
      example:
        id: 0
        title: title
        body: body
        userId: 6
      properties:
        id:
          format: int64
          type: integer
        userId:
          format: int64
          type: integer
        title:
          type: string
        body:
          type: string
      required:
      - id
      - name
      type: object
    Posts:
      items:
        $ref: '#/components/schemas/Post'
      type: array
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
